/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xcoders.view;

import com.xcoders.ws.PokerException;
import com.xcoders.ws.PokerWS;
import com.xcoders.ws.PokerWSService;
import javax.swing.JOptionPane;

/**
 *
 * @author ravindu
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setSize(1024, 768);
        panelSignIn.setVisible(false);
        userRegister.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelSignIn = new javax.swing.JPanel();
        btnSignIn = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnCancelSignIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        userRegister = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelButtons = new javax.swing.JPanel();
        btnOptions = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMultiplayer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crazy pine apple 8 or better poker");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSignIn.setBackground(new java.awt.Color(1, 1, 1));
        panelSignIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));

        btnSignIn.setText("Sign In");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancelSignIn.setText("Cancel");
        btnCancelSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSignInActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("User name");

        txtUserName.setToolTipText("sasas");

        javax.swing.GroupLayout panelSignInLayout = new javax.swing.GroupLayout(panelSignIn);
        panelSignIn.setLayout(panelSignInLayout);
        panelSignInLayout.setHorizontalGroup(
            panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignInLayout.createSequentialGroup()
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSignInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelSignIn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSignInLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword))))
                .addGap(20, 20, 20))
            .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSignInLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(428, Short.MAX_VALUE)))
        );
        panelSignInLayout.setVerticalGroup(
            panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignInLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnSignIn)
                    .addComponent(btnCancelSignIn))
                .addContainerGap())
            .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSignInLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel2)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        getContentPane().add(panelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 600, 200));

        userRegister.setBackground(new java.awt.Color(0, 0, 0));
        userRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        userRegister.setAlignmentX(0.5F);
        userRegister.setAlignmentY(0.5F);
        userRegister.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        jLabel4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userRegisterLayout = new javax.swing.GroupLayout(userRegister);
        userRegister.setLayout(userRegisterLayout);
        userRegisterLayout.setHorizontalGroup(
            userRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userRegisterLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userRegisterLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userRegisterLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userRegisterLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButton1))
        );
        userRegisterLayout.setVerticalGroup(
            userRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userRegisterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(userRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton1))
        );

        getContentPane().add(userRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 600, 200));

        panelButtons.setBackground(new java.awt.Color(255, 0, 0));
        panelButtons.setOpaque(false);

        btnOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g3.png"))); // NOI18N
        btnOptions.setBorder(null);
        btnOptions.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g8.png"))); // NOI18N
        btnOptions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g13.png"))); // NOI18N

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g4.png"))); // NOI18N
        btnHelp.setBorder(null);
        btnHelp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g9.png"))); // NOI18N
        btnHelp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g14.png"))); // NOI18N

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g5.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/001.png"))); // NOI18N
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g15.png"))); // NOI18N

        btnMultiplayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g2.png"))); // NOI18N
        btnMultiplayer.setBorder(null);
        btnMultiplayer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g7.png"))); // NOI18N
        btnMultiplayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/g12.png"))); // NOI18N
        btnMultiplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMultiplayer)
                    .addComponent(btnExit)
                    .addComponent(btnHelp)
                    .addComponent(btnOptions))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMultiplayer)
                .addGap(18, 18, 18)
                .addComponent(btnOptions)
                .addGap(18, 18, 18)
                .addComponent(btnHelp)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(panelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 290, 250));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/com/xcoders/images/background_main_menu.png")))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSignInActionPerformed
        panelSignIn.setVisible(false);
    }//GEN-LAST:event_btnCancelSignInActionPerformed

    private void btnMultiplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplayerActionPerformed
        panelSignIn.setVisible(true);
    }//GEN-LAST:event_btnMultiplayerActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        panelSignIn.setVisible(false);
        userRegister.setVisible(true);
        try{
            PokerWS pws = new PokerWSService().getPokerWSPort();          
            pws.register(txtUserName.getText().trim(), txtPassword.getText());       
            this.dispose();
        }catch(PokerException pe){
           JOptionPane.showMessageDialog(this,pe.getMessage(), "Registration Failed",  JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Unable to connect to poker server.Please check your internet connection!", "Network Error",  JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }

        /*
        
        try{          
            PokerWS pws = new PokerWSService().getPokerWSPort();
            Long playerId = pws.login(txtUserName.getText().trim(), txtPassword.getText());
            Integer tableId = pws.joinGame(playerId);
            new TableFrame(playerId, tableId).setVisible(true);
            this.dispose();
       }catch(PokerException pe){
           JOptionPane.showMessageDialog(this,pe.getMessage(), "Login Failed",  JOptionPane.ERROR_MESSAGE);
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Unable to connect to poker server.Please check your internet connection!", "Network Error",  JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
        */
        
                
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelSignIn;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnMultiplayer;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelSignIn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel userRegister;
    // End of variables declaration//GEN-END:variables
}
